NanoVNA-Saver/nanovna-saver

Pipfile
requirements.txt

Right now the installation instructions call out the two python
external dependencies (pyserial and PyQT5), but assumes the dependencies
are installed globally.
I suggest adding a requirements file (and its pipenv equivalent:
Pipfile) so folks can use the normal python installation tools.
This pull request adds those files.  Tested under WSL and Ubuntu 18.

Add Pipfile (for pipenv) and requirements.txt (for pip) to make installation a bit less manual.

---

README.md
nanovna-saver.py

There was a question on the nanovna list showing confusion about which
file was indended to be the executable.  This commit makes three small
changes to ease that issue.
* it updates the README with a run instruction
* it grants nanovna-saver.py executable permission
* it adds '#! /bin/env python' to the start of nanovna-saver.py so it is
directly executable.

Added #! to nanovna-saver, updated README

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
NanoVNASaver/NanoVNASaver.py
NanoVNASaver/RFTools.py
README.md
setup.py

I've modified the RFTools frequency parser to cope with more SI prefixes and
added a new formatter to shorten frequency values for easier human readabilities.
73
DG5DBH

Use shortend frequency values in sweep input

---

NanoVNASaver/NanoVNASaver.py
NanoVNASaver/RFTools.py

formatFixedFrequency limits the maximum digits displayed to fit return values within space available. For sweep frequencies this can result in loss of accuracy. formatSweepFrequency instead provides the smallest return value that does not result in loss of accuracy, but allows for padding trailing zeroes if desired.

Separate formatFrequency for Sweep values

---

NanoVNASaver/RFTools.py

I've modified Datapoint to supply optional native python complex numbers via a z impedance property
and used cmath for RFTool calculations

Use python native complex numbers in RFTools

---

NanoVNASaver/NanoVNASaver.py

- Provide different titles for the save buttons
- Use the selected file type as the suffix filter of the save-as dialog
Resolve #148 - Assist novice users with clarifying save-as S1P and S2P file types

Differentiate S1P vs. S2P file save

---

NanoVNASaver/Chart.py
NanoVNASaver/NanoVNASaver.py

1. The chart image is saved only if explicitly specify the png extension. This patch solves this problem.
2. Remove white background from About window. It doesn't look pretty in a dark theme.

Add default extension (png) when saving image

---

NanoVNASaver/Analysis/AntennaAnalysis.py
NanoVNASaver/NanoVNASaver.py

This repairs the issue I just added (crash when click connect with no device) and it repairs a small typo in AntennaAnalysis that stops execution.

repair crash with no device attached

---

NanoVNASaver/Analysis/Analysis.py
NanoVNASaver/Analysis/PeakSearchAnalysis.py
NanoVNASaver/Analysis/VSWRAnalysis.py
NanoVNASaver/RFTools.py
NanoVNASaver/Windows/AnalysisWindow.py

Working to HWEF  ... request for comment
Some fix to PeakSearch , not mine but seems to work to me.
Added ResonanceAnalysis to find X==0 , may be better add to PeakSearch
Added HWEF Analysis, find X==0 near HI Impedance
also try to compare previous sweep and show ( only in log for now ) delta values.
Intended Usage:
- sweep  antenna base
- HWEF Analysis to find resonances
- do changes on antenna and sweep
- HWEF Analysis and find changes
see log for delta
- repeat
73

Some Analysis

---

NanoVNASaver/Hardware/NanoVNA.py
NanoVNASaver/Hardware/VNA.py

MUST try with version != original nanovna !!!
see https://github.com/NanoVNA-Saver/nanovna-saver/issues/347
Only for V1 read frequencies,
for other must overwrite  _get_running_frequencies()

try to read initial frequencies

---

NanoVNASaver/Hardware/NanoVNA_H4.py

Small change to enable 401 points on H4.

401 sweep points

---

NanoVNASaver/Hardware/AVNA.py
NanoVNASaver/Hardware/NanoVNA.py
NanoVNASaver/Hardware/NanoVNA_F.py
NanoVNASaver/Hardware/NanoVNA_F_V2.py
NanoVNASaver/Hardware/NanoVNA_H.py
NanoVNASaver/Hardware/NanoVNA_H4.py
NanoVNASaver/Hardware/NanoVNA_V2.py
NanoVNASaver/Hardware/VNA.py
NanoVNASaver/NanoVNASaver.py
NanoVNASaver/Windows/SweepSettings.py

As of firmware version 1.0.2 (tag 20210214) the output power of the TX ADF4350 can be configured via USB (register 0x42).  Add support for this setting in NanoVNASaver.
In order to correctly show the frequencies that will be affected by the setting we need to know the maximum stop frequency of the VNA. Add this information for all supported VNA models.
**WARNING**: The automatic first sweep after connecting to the VNA will be performed at maximum power (default). Sensitive equipment should not be connected until after NanoVNASaver has connected to the NanoVNA v2 and the setting has been changed.
Screenshot of the modified sweep settings window while connected to a NanoVNA v2 with firmware 1.0.2:
The branching model isn't quite clear to me. The Development branch is lagging behind the …

Add support for setting TX power on NanoVNA v2

---

NanoVNASaver/Charts/RI.py

Resolves plotting issue as discussed in #165
A typo results in printing the imaginary axis label as minimum value for the real axis

Fixing minimum axis label value in RI charts

---

.gitignore
NanoVNASaver/Marker/Values.py
NanoVNASaver/Marker/Widget.py

Adds new markers for
S21 |Z| shunt
S21 |Z| series
S21 R+jX shunt
S21 R+jX series
issue https://github.com/NanoVNA-Saver/nanovna-saver/issues/165

Add new s21 markers for |Z| and R+jX

---

NanoVNASaver/Hardware/Hardware.py
NanoVNASaver/Marker/Widget.py
NanoVNASaver/NanoVNASaver.py

my -H with DiSlord's NanoVNA-D FW (V.1.0.65) responds to `\r` with
````
?
ch> 
````
which lead to this logger error:
````
NanoVNASaver.Hardware.Hardware - ERROR - No VNA detected. Hardware responded to CR with: 
?
ch> 
````

Format shrinking and better -H detection

---

NanoVNASaver/Formatting.py
NanoVNASaver/Marker/Delta.py
NanoVNASaver/Marker/Widget.py

Calculates the admittance as 1/Z, checks for Z=0.
Unit is "S" for Siemens as Omega^-1 was running into space issues in the currently available formatting of the marker window
Fixes #445

Change calculation of admittance value and unit in marker plotting code

---

NanoVNASaver/Calibration.py
NanoVNASaver/Windows/CalibrationSettings.py

Fix division on zero in Open calibration standard C0 value = 0
Implement Load C calibration standart use

Calibration standarts fix and improve

---

NanoVNASaver/Version.py

The comparison operators (`<`, `>`, etc.) are not translated 1:1 to customisation methods (`__lt__`, `__gt__`, ...) in Python. Instead the type of the operands plays a role in determining on which of the two sides the customisation method is invoked (see [Python Language Reference section 3.3.1](https://docs.python.org/3/reference/datamodel.html#object.__lt__)). This means `a > b` can end up invoking `b.__lt__(a)` rather than `a.__gt__(b)`.
This behaviour can causes infinite recursion in `Version.__lt__()`:
```
2022-03-07 13:47:52,087 - NanoVNASaver.Hardware.NanoVNA_V2 - ERROR - Timeout reading version registers
Traceback (most recent call last):
File "/home/sascha/nanovna-saver/NanoVNASaver/Controls/SerialControl.py", line 73, in serialButtonClick
self.connect_device()
File …
```

Version: avoid infinite recursion

---

README.md

Add additional indentation to force code formatting of command lines. (Could use triple-backticks instead.)

Fix command-line formatting in README.md

---

NanoVNASaver/Charts/Frequency.py

Closes #500
NanoVNA-saver crashes per below when getPlotable returns a float.
getPlotable is always followed by a call to drawLine(self, int, int,
int, int), so it needs to return ints.
Cast getPlotable return values to int in all cases.
Traceback (most recent call last):
File "/home/blinken/co/nanovna-saver/NanoVNASaver/Charts/Frequency.py", line 447, in paintEvent
self.drawValues(qp)
File "/home/blinken/co/nanovna-saver/NanoVNASaver/Charts/VSWR.py", line 144, in drawValues
self.drawData(qp, self.data, Chart.color.sweep)
File "/home/blinken/co/nanovna-saver/NanoVNASaver/Charts/Frequency.py", line 641, in drawData
qp.drawLine(prevx, prevy, new_x, new_y)
TypeError: arguments did not match any overloaded call:
drawLine(self, QLineF): argument 1 has unexpected type 'int'
drawLine(self, …

getPlotable, cast return values to int

---

NanoVNASaver/Charts/RI.py

I made an inductor that the NanoVNA measures as having a negative real resistance, so the automatic scaling of the plot doesn't work:
Adding this change fixes it so that it does scale properly:

Add negative real resistance for proper graph scaling

---

test/test_settings.py

The test compares two instances with equal data, but it is expected to compare two different instances.
Signed-off-by: Frank Kunz <mailinglists@kunz-im-inter.net>

Fix test_restore_dataclass

---

.gitignore
Makefile

this allows to safely install, update and remove the program
Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>
Issue Number: #517
- `make deb` creates `nanovnasaver_*.deb`
- `make debinstall` installs the package (`sudo apt` must be enabled)
- `make debuninstall` uninstalls the package (`sudo apt` must be enabled)
- `make clean` removes all artifacts of the build but keeps the `*.deb`
- `make distclean` removes all artifacts of the build incl. the `*.deb`

feat: add a Makefile to build a simple debian package

---

Makefile
NanoVNASaver/Hardware/Hardware.py

Issue Number:  NanoVNA V2 Plus5 not recognized on Windows with last FW 20220814.
- VNA appears now as 'COMXX (S-A-A-2)' in the Serial port control section of thr GUI
- Now device can be connected without error
-

Support of NanoVNA V2 Plus5 on Windows (FW 20220814)

---

NanoVNASaver/Charts/Chart.py
NanoVNASaver/Defaults.py
NanoVNASaver/Windows/DisplaySettings.py
requirements.txt

- Dataclasse with QColor objects would only work with a default_factory in Python dataclasses

dataclass fix for python3.11 compatability

---

NanoVNASaver/Windows/About.py
NanoVNASaver/Windows/AnalysisWindow.py
NanoVNASaver/Windows/CalibrationSettings.py
NanoVNASaver/Windows/DeviceSettings.py
NanoVNASaver/Windows/DisplaySettings.py
NanoVNASaver/Windows/Files.py
NanoVNASaver/Windows/SweepSettings.py
NanoVNASaver/Windows/TDR.py

Issue Number: #485
@kencormack wrote:
On smaller displays (ie: a 7" 800x480 touchscreen), certain screens, such as the "Display settings" screen, are not downward scroll-able. Consequently, options to select "Displayed charts", "Markers", and such, are not available/cannot be accessed.
- All sub windows can be resized and get scrollbars if too small
Example of resized Calibration window:

Proposal for #485 - make all windows scrollable

---

NanoVNASaver/Charts/Frequency.py

The correct order of parenthesises in the getYPosition() method
Charts like Serial C and Serial L are broken due to a bug/typo in the logic computing vertical chart position. Serial C does not show anything and Serial L in inverted.
Charts show correct L and C
-
-
-

getYPosition fix

---

NanoVNASaver/Charts/RI.py
NanoVNASaver/Charts/RIMu.py
NanoVNASaver/Charts/RIZ.py
NanoVNASaver/Charts/RIZSeries.py
NanoVNASaver/Charts/RIZShunt.py
NanoVNASaver/Charts/__init__.py
NanoVNASaver/NanoVNASaver.py
NanoVNASaver/SweepWorker.py
README.md

This change adds a new plot type "S11 mu" to show the complex permeability of an inductor core.
Cores are measured by putting one or more windings on them and measuring the S11.
In order to correctly calculate the permeability the user also needs to set the dimensions of the core (cross-section and effective length) and the number of windings.  This can be done by opening the context menu for the plot (right click on the graph area).
The core dimensions can either be measured from the core directly using calipers.
More info on how the calculations work are available in #206
A brief description of the new measurement method is also added to the main project README.
Issue Number: fixes #206 
- The Charts/RI.py was split into a generic …

Measuring mu' and mu'' of ferrite cores

---

src/NanoVNASaver/__main__.py

The file is not intended for direct execution,
not installed in the path,
and not marked as executable.
Its extension is sufficient for editors to trigger syntax highlighting.
The shebang seems to only trigger warnings on systems wher /bin/env is unavailable (it may be in /usr/bin for example).
Code style update
Not a breaking change?

__main__.py: remove /bin/env shebang

---

docs/man/NanoVNASaver.1

Some redistributors want a manual page for each executable in path.
The installation path may differ accross systems, so the manual page is not installed by default.
Documentation content changes
Not a breaking change.
The path is arbitrary.
Sphinx can generate documentation in the man page format, but this is unrelated with the expected documentation of command line options.

Add an UNIX-style manual page

---

src/NanoVNASaver/Hardware/NanoVNA_V2.py
src/NanoVNASaver/Settings/Sweep.py

NamedTuples are immutable either use _replace or use the class itself.
- Single
- [X ] Bugfix
- Bug updating sweep.properties value
- Bug updating VNA.version value
- Sweep settings now work as expected.
- Hardware LiteVNA64 hardware is now properly initialized 
- [X ] No
Apparently python 3.10 is more strict in checking immutable states
The NanoVNA_V2.py driver was probably missed by an update.

fix: sweep settings and hw version update

---

nanovna-saver.py

nanovna-saver.py can be called from outside the source directory. The module import path needs to be resolved relative to the source directory, not relative to the current working directory of the process.
Fixes: b0110002 ("moved to pyscaffold directory structure")
This branch is based on the commit before the transition to PyQt6 as the latter is not available in Debian stable (Bullseye).
When executing `nanovna-saver.py` from outside the source directory but without installing it, importing `main` fails:
```
I have no name!@nanovna:~/nanovna-data$ cd ~/nanovna-data && python3 ~/nanovna-saver/nanovna-saver.py -d
Traceback (most recent call last):
File "/home/sascha/nanovna-saver/nanovna-saver.py", line 29, in <module>
from …
```

nanovna-saver.py: fix execution from outside source directory

---

src/NanoVNASaver/Marker/Widget.py
src/NanoVNASaver/Windows/DisplaySettings.py

At program start many error messages are written on terminal:
`Could not parse stylesheet of object QGroupBox...`
Header lines of marker boxes are not colored.
Sweep color does not change without close/re-open (#596)
No error messages, colored header lines of marker boxes (commit 1)
Fix #596: Update sweep color immediately when changed in display settings (commit 2)

fix "Could not parse stylesheet of object QGroupBox..." error

---

src/NanoVNASaver/NanoVNASaver.py
src/NanoVNASaver/__main__.py

Command line option `--auto-connect` or `-a` connects automatically if one device was detected - useful in most cases where you have only one NanoVNA connected to the PC. If there are more NanoNVAs or a NanoNVA and a tinySA connected, the user has to select from the combo list.

option --auto-connect, connect automatically if one device detected

---

src/NanoVNASaver/Settings/Sweep.py
tests/test_sweep.py

6eb24f23 from merge request 625
made NamedTuple an ancestor of Properties, adapting the imports and tests.
d09b55e1 from merge request 628
removed it but forgot to remove the related changes.
- [ x] Bugfix
- [ x] Code style update (formatting, renaming)
- [ x] No

Adapt sweep settings imports and tests to source changes

---

nanovna-saver.py

The nanovna-saver.py script is ignored by setup.cfg, its only purpose is to test the version in the source directory.
According to https://setuptools.pypa.io/en/latest/history.html, pkg_resources.py2warn has been removed from setuptools in 2020

Simplify the in-source launcher script

---

src/NanoVNASaver/Hardware/JNCRadio_VNA_3G.py
src/NanoVNASaver/Hardware/SV4401A.py
src/NanoVNASaver/Hardware/SV6301A.py
src/NanoVNASaver/Windows/DeviceSettings.py

Updated datapoints dropdown to now show only their respective minimums, the 'typical' 101, device default 501 and maximum 1001 points. Users may choose any other values between min and max not seen in the dropdown list using the custom datapoints option.
These devices now use their factory default 501 datapoints as their initial datapoints value.
- [ X] Feature
Issue Number: #661
-
-
-
- [ X] No

With current firmware, the JNCRadio, SV4401A, SV6301A devices allows 1001 datapoints

---

src/NanoVNASaver/Controls/SweepControl.py
src/NanoVNASaver/NanoVNASaver.py
src/NanoVNASaver/Settings/Sweep.py
src/NanoVNASaver/SweepWorker.py
src/NanoVNASaver/Windows/DeviceSettings.py
src/NanoVNASaver/Windows/SweepSettings.py
tests/test_sweep.py

The two first commits are trivial (and could be submitted separately if needed).
The third one is a proof of concept for one of the ideas in issue #657.
The header describes why it can probably not be applied yet.
No  breaking change (hopefully).

Sweep.py: add getters and setters for private fields

---

.github/workflows/release_win.yml

Added -i icon_48x48.ico to the release_win.yml github action.
- [X ] Feature
Up to now, the nanovna-saver.exe Windows application gets created with a generic python application icon. This change should allow pyinstaller to pick up the the icon_48x48.ico file recently added.
Issue Number: #670 
-
-
-
- [X ] No

Add the nanosaver project icon to resulting Windows application.

---

.github/workflows/release_win.yml

When I build (for Windows) the version from commit `a04d6d9b3995eabe26a41c9d5abc56678dd8b035` the final executable show the follow error if you try to execute:
```txt
Traceback (most recent call last):
File "nanovna-saver.py", line 32, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
File "NanoVNASaver\__main__.py", line 31, in <module>
ModuleNotFoundError: No module named 'PyQt6.sip'
```
With this changes on build, the `pyinstaller` find correctly the Qt6 dependency and link on the final executable. 
`pyinstaller` build the executable, but can't correct link the PyQt6.sip dependency.
Issue Number: 1
`pyinstaller` find PyQt6.sip and Qt6 dependency, correctly.
This change only affects the Windows …

FIX build for Windows executable

---

AUTHORS.rst
src/NanoVNASaver/Settings/Sweep.py
tests/test_sweep.py

In case that `logarithmic sweep` is enabled in the sweep settings, the (internally linearly sampled) segments of 101 data points do not have a proper logarithmic spacing. When multiple segments are used, the quotient of end_frequency by start_frequency for all segments should be the same. Also a small error in the get_frequency() iterator is fixed.
See also:  https://github.com/NanoVNA-Saver/nanovna-saver/issues/701
- [] Feature
In case that `logarithmic sweep` is enabled in the sweep settings, the (internally linearly sampled) segments of 101 …

Fix frequency calculation at logscale sweeps

---

docs/INSTALLATION.md
src/NanoVNASaver/Windows/About.py

- [] Feature
Performed a virgin install of Lubuntu 24.04 LTS and followed the steps in INSTALLATION.md to create the python3 virtual environment.  Starting nanovna-saver app resulted in core dump. Seems the culprit is a missing installation of libxcb-cursur-dev. Once that installed, nanovna-saver app start and runs.
Notices a warning in checking for updates. Fixed my regexp search as well. 
Application run starts up and runs without core dumping or emitting warning about regexp.
-
-
-
- [] Yes

Fix a core dump on startup and warning on rexexp search for version number

---

src/NanoVNASaver/About.py
src/NanoVNASaver/Windows/TDR.py

There is a bug with About.py which results in the program not being able to run if you call `python nanovna_saver.py`. The bug is caused by the path for setuptools-scm not being correctly defined. The path should be `../..` because the .git folder is two directories below, not `..`
There is also a bug with the math for TDR. In the current state, the TDR is not able to distinguish between open and short. In the new code, the TDR is now able to calculate impedance.
- [*] Bugfix
- [] Feature
For the About.py bug: a LookupError is thrown by …

Fix About.py bug and fix math for TDR

---

src/NanoVNASaver/About.py
src/NanoVNASaver/Charts/TDR.py
src/NanoVNASaver/Windows/TDR.py

- [] Bugfix
- [*] Feature
The user is only allowed to plot the magnitude of the impedance (or |Z|)
The user is now allowed to select from a menu whether they want to plot |Z|, S11, or VSWR. This would allow the user to display their data in a different format
- [] Yes
- [*] No
Here is what everything looks like now:
Maybe in the future you can plot real/imaginary?

Adding more features to TDR window

---

src/NanoVNASaver/Charts/TDR.py
src/NanoVNASaver/Windows/TDR.py

- [*] Bugfix
- [*] Feature
One of the bugs is that if the length to a discontinuity is small, the TDR does not measure correctly. This is because the impulse response looks like a pulse, and half of the pulse is not integrated because it is centered around zero, and only positive time values are added. I solved this issue by also adding the negative time values. This way, the entire pulse is integrated and we get a step response of 1 instead of 0.5. Normally, the negative time values are very small so it doesn't seem like any bad behavior happens …

Fix TDR math again

---

src/NanoVNASaver/Calibration.py
src/NanoVNASaver/Touchstone.py
src/NanoVNASaver/Windows/CalibrationSettings.py

- [] Bugfix
- [*] Feature
Right now, you can either use ideal values or use coefficients (if your cal components are not ideal). However, if you use a VNA to measure your calibration kit, you just get a S1P file. While it is possible to derive the coefficients for the short and open, the load seems to be more complicated, especially at higher frequencies. 
You are now able to input S1P files for calibration.
- [] Yes
- [*] No
I imported this S11 file for the open:
My results after calibration:
You can see that at 8GHz the phase is roughly 10 …

Allow Touchstone files for calibration

---

src/NanoVNASaver/Controls/SerialControl.py
src/NanoVNASaver/Controls/SweepControl.py
src/NanoVNASaver/NanoVNASaver.py

Disable some buttons when device is not connected:
- disable `Serial -> Manage` and` Sweep -> Start` button when device is not connected
- disable `Serial -> Connect` button when port was not selected
- [] Feature
There are two issues:
- it's possible to click connect button when no ports selected (e.g. no any physical devices connected)
- it's possible to open serial management OR start sweep when no VNA connected
These crash application. 
Disable connect button when no any physical devices existed.
Disable serial management …

chore: improve sweep and serial controls state

---

src/NanoVNASaver/Hardware/Hardware.py
src/NanoVNASaver/Hardware/NanoVNA_F_V3.py
src/NanoVNASaver/Hardware/VNA.py

Add new hardware support for NanoVNA F V3
- [] Bugfix
- NanoVNA saver can not show data points more than 101 on NanoVNA F V3
- SN number not showing up
Issue Number: 711
- Increased the sweeping data points upto 801
- Able to show correct SN number for NanoVNA F V3
Discussion(issue) had been open from here: https://github.com/NanoVNA-Saver/nanovna-saver/issues/711

Add support for NanoVNA F V3 for reaching valid data points upto 801

---

src/NanoVNASaver/Hardware/Hardware.py
src/NanoVNASaver/Hardware/NanoVNA_F_V3.py
src/NanoVNASaver/Hardware/TinySA.py
src/NanoVNASaver/Hardware/VNA.py

- Add support for Spectrum Analyzer tinySA Ultra+ ZS-407, ZS-406, ZS-405 and tinySA and fix crashing due to operations on Integer
- Add correct model type and firmware version number shown in nanovna-saver app
- Add a property called `hardware_revision` in **class** `TinySA_Ultra` for future need which would be displayed in the __**Device settings**__ -> **Status**
This is an onward pull-request after my another pull-request for adding support for NanoVNA-F V3 from here: <https://github.com/NanoVNA-Saver/nanovna-saver/pull/751>
Crashing due to bad operations on Integer when testing with a tinySA Ultra+ ZS-407
- Display correct model type, firmware version of all tinySA (Ultra or Ultra+)
- Fix crashing
**Sometimes it's …

Add support for tinySA Ultra+ ZS-407, ZS-406, ZS-405 and tinySA and fix crashing due to operations on Integer

---

src/NanoVNASaver/Windows/ui/about.py
src/NanoVNASaver/Windows/ui/about.ui

e.g. see screenshot from https://github.com/NanoVNA-Saver/nanovna-saver/issues/773#issuecomment-2629026606
- [] Feature
Some areas in an `About` window was different background color.
Whole window area has the same styling
- [] Yes

fix: widget styles for about window

---

src/NanoVNASaver/Defaults.py
src/NanoVNASaver/NanoVNASaver.py
tests/test_settings.py

Fix application settings restoring
It's a followup for https://github.com/NanoVNA-Saver/nanovna-saver/pull/778, MyPy absence is bit frustrating
It fixes https://github.com/NanoVNA-Saver/nanovna-saver/issues/777 and was mentioned in https://github.com/NanoVNA-Saver/nanovna-saver/issues/768
- [] Feature
- some of settings (e.g. font size) are not restored between run sessions
- sweep configuration is not saved between run sessions
- app crashes right before exit
Issue Number: [777](https://github.com/NanoVNA-Saver/nanovna-saver/issues/777)
settings …

fix: settings restoring (Part 2)

---

src/NanoVNASaver/Controls/SweepControl.py
src/NanoVNASaver/NanoVNASaver.py
src/NanoVNASaver/Settings/Sweep.py
src/NanoVNASaver/SweepWorker.py

fix for https://github.com/NanoVNA-Saver/nanovna-saver/issues/773 bug
- [] Feature
- unable to stop continues sweeping
- unable to close app gracefully when sweeping in progress
Issue Number: https://github.com/NanoVNA-Saver/nanovna-saver/issues/773
- The "stop" button stops the next sweep cycle
- application try to stop sweep cycle before exit (waits 10 sec before hard interruption) 
- [] Yes
`SweepState` usages should be reviewed, looks like QtThread.isRunning() may be used instead.

fix: sweep worker stopping

---

README.rst
src/NanoVNASaver/Charts/Chart.py
src/NanoVNASaver/Charts/Frequency.py
src/NanoVNASaver/Charts/TDR.py
src/NanoVNASaver/Windows/SweepSettings.py
src/NanoVNASaver/Windows/TDR.py

- Application crashed, when trying to draw zoom rectangle (ctrl-modifiers) in TDR window
- Panning with keys was not possible
- No choice of window function for fft
- Zooming by scrolling the mouse wheel was not working
- Fixed crash, ctrl-zooming now possible.
- One can pan the graph using arrow keys
- One can zoom using the mouse wheel
- Drop down with different window functions (kaiser with different betas to mimic nanovna, hanning, blackman)

Zooming and panning in TDR window and choosing fft window type

---

README.rst
src/NanoVNASaver/Charts/TDR.py
src/NanoVNASaver/Windows/TDR.py

TDR graph: Tick labels were not sync with cable end mark and/or user mark depending on the zoom level.
Only TDR graph:
- Tick labels, end mark and user mark are now consistent
- Enhanced automatic calculation of tick spacing
- Enhanced label drawing with semi transparent background for better readability
- Speedup of graph drawing when lines are used: FFT points reduced from 2^14 to 2^12

TDR: Synchronize ticks and marker

---

docs/conf.py
src/NanoVNASaver/Charts/TDR.py
src/NanoVNASaver/Hardware/Hardware.py
src/NanoVNASaver/Hardware/NanoVNA_F_V2.py
src/NanoVNASaver/Hardware/NanoVNA_H4.py
src/NanoVNASaver/Hardware/TinySA.py
src/NanoVNASaver/Hardware/VNA.py
src/NanoVNASaver/Windows/DeviceSettings.py
src/NanoVNASaver/Windows/Screenshot.py
src/NanoVNASaver/Windows/TDR.py
tests/Hardware/test_litevna_64.py
tests/conftest.py
tests/test_analytics.py
tests/test_formatSweepFrequency.py
tests/test_formatting.py
tests/test_parseFrequency.py
tests/test_rftools.py
tests/test_settings.py
tests/test_sitools.py
tests/test_sweep.py
tests/test_touchstone.py
tests/test_truncate.py
tests/utils/test_app_versions.py
tests/utils/test_version.py

chore: needed fixes due to newly integrated PRs

---

src/NanoVNASaver/Hardware/NanoVNA_F_V2.py

Add init_features to fix SN not showing in device setting window
Add return statement at end of get_features function.  Both changes in hardware/NanoVNA_F_V2
- [X ] Bugfix
Issue Number: 38
After connecting device to usb and selecting "manage" button, info box now has SN info.
Selecting ComboBox for valid sweep points show all options, not just 101.
-
-
-
- [X ] No
I've only tested in Windows 10.  This is my first PULL request so I apologize in advance for any improper actions!

Add missing return in hardware/NanoVNA_F_V2.py function get_features
