NanoVNA-Saver/nanovna-saver

- NanoVNASaver.py
- Added some min/max stats for S11 VSWR and return loss, and S21 gain.
> - S12 is really S21!

- NanoVNASaver/Calibration.py
- NanoVNASaver/Chart.py
- NanoVNASaver/LogMagChart.py
- NanoVNASaver/Marker.py
- NanoVNASaver/NanoVNASaver.py
- NanoVNASaver/SmithChart.py
- NanoVNASaver/SweepWorker.py
- NanoVNASaver/Touchstone.py
- NanoVNASaver/__main__.py
- README.md
- setup.cfg
- setup.py
- Moved files into project folder named "NanoVNASaver"
- Added requirements
- Adjusted readme a little
> Prep for pip packaging

- NanoVNASaver/NanoVNASaver.py
> Bugfix: Handle more than 6 saved markers

- .gitignore
- NanoVNASaver/RFTools.py
- NanoVNASaver/SITools.py
Hello, 
many thanks for your great software for the NanoNVA.
As I saw you are still experimenting with numberformating in RFTools.
So I've cleaned up my previous suggestion and refactored this out
in a SITools module.
It should be capable of all current parsing and formatting needs in this program.
Imho it's far more readable and flexible as my existing solution.
Perhaps you'll give it a try.
> SI formatting and parsing class

- NanoVNASaver/RFTools.py
- NanoVNASaver/SITools.py
I have added parsing of infinity and moved your Khz option as parameters to the Format of Value class.
Modified RFTools to use it with sloppyness.
> sloppy SI parsing to allow common human errors

- NanoVNASaver/NanoVNASaver.py
Clamp marker count to sane values when read from settings.
Fixes bug #114
> Clamp marker count between 1 and 1000

- NanoVNASaver/NanoVNASaver.py
> Bugfix: stuck field selection

- NanoVNASaver/Formatting.py
- NanoVNASaver/Marker/Settings.py
- NanoVNASaver/Marker/Widget.py
Implements feature request #150
> Added S11 |Z| and |S11|/|S21| markers

- NanoVNASaver/About.py
- NanoVNASaver/Calibration.py
- NanoVNASaver/NanoVNASaver.py
Need Value of isolation before calculation of through corrections
> Fixed through calibration

- NanoVNASaver/Analysis/AntennaAnalysis.py
- NanoVNASaver/Analysis/VSWRAnalysis.py
- NanoVNASaver/Windows/AnalysisWindow.py
- nanovna-saver.py
Hi,
only a sample to lock or concordate modification.
With MagLoopAnalysis I want "follow" and zoom on minimum.
scan 3-30 MHz
find minimum
scan center minimum + initial span
find minimum , if no minimum increase span and goto 3
show data es Q
ajust loop capacitor
goto 3
I also want to create EndFedAnalisis to find N minimum and zoom on those minimum.
It will help if Chart can have its data to show.
Sorry for my bad english, but with some ask I can explain better
> refactoring Vswr Analysis

- NanoVNASaver/Calibration.py
- NanoVNASaver/Hardware/AVNA.py
- NanoVNASaver/Hardware/Hardware.py
- NanoVNASaver/Hardware/NanoVNA.py
- NanoVNASaver/Hardware/NanoVNA_F.py
- NanoVNASaver/Hardware/NanoVNA_V2.py
- NanoVNASaver/Hardware/Serial.py
- NanoVNASaver/Hardware/VNA.py
- NanoVNASaver/Hardware/__init__.py
- NanoVNASaver/NanoVNASaver.py
This should fix the s21 save bug
Also use with for serial lock to clean up locking code
> Bugfixes and simplifications

- .gitignore
- CHANGELOG.md
- NanoVNASaver/About.py
- NanoVNASaver/Analysis/AntennaAnalysis.py
- NanoVNASaver/Analysis/BandPassAnalysis.py
- NanoVNASaver/Analysis/BandStopAnalysis.py
- NanoVNASaver/Analysis/HighPassAnalysis.py
- NanoVNASaver/Analysis/LowPassAnalysis.py
- NanoVNASaver/Analysis/PeakSearchAnalysis.py
- NanoVNASaver/Analysis/SimplePeakSearchAnalysis.py
- NanoVNASaver/Analysis/VSWRAnalysis.py
- NanoVNASaver/Hardware/NanoVNA_H4.py
- NanoVNASaver/Hardware/NanoVNA_V2.py
- NanoVNASaver/Hardware/Serial.py
- NanoVNASaver/Hardware/VNA.py
- NanoVNASaver/NanoVNASaver.py
- NanoVNASaver/Settings.py
- NanoVNASaver/SweepWorker.py
- NanoVNASaver/Windows/CalibrationSettings.py
- NanoVNASaver/Windows/DeviceSettings.py
- NanoVNASaver/Windows/TDR.py
* Refactored SweepWorker so that multi segment sweep don't resize Charts
during run.
Should fix resetting markers to sweep start frequence.
* Change of Datapoints in DeviceSettings is reflected in step size
> Release v0.3.5

- NanoVNASaver/About.py
- NanoVNASaver/Hardware/NanoVNA.py
- NanoVNASaver/Hardware/NanoVNA_H4.py
Skipped v0.3.5 as there are oddities with classic VNAs
> v0.3.6-pre

- NanoVNASaver/About.py
- NanoVNASaver/Hardware/VNA.py
- NanoVNASaver/NanoVNASaver.py
- NanoVNASaver/SITools.py
- NanoVNASaver/SweepWorker.py
- NanoVNASaver/Widgets/SweepControl.py
- NanoVNASaver/Windows/DisplaySettings.py
Implements Feature #147 
Renamed count to segments in SweepWorker/SweepControl
> Case-insensitive entry of frequency units

- NanoVNASaver/Controls/MarkerControl.py
- NanoVNASaver/NanoVNASaver.py
Also same fix for Marker status buttons not updating.  Apparently this is a problem only with Mac OS 10.14 and higher.
> Fix for issue #172 where Serial Connect buttons don't update.

- README.md
We've had a couple of people fail to install the mac version and I think just some extra verbiage and a few tweaks helps a bunch with this. I've written an updated Mac portion of the readme but it conflicts slightly with the changes pending so I'm happy to update it when testing is integrated.
Mark
> Mac readme update

- requirements.txt
- setup.py
> use latest scipy (seems too work again)

- NanoVNASaver/Charts/MagnitudeZ.py
- NanoVNASaver/Charts/MagnitudeZSeries.py
- NanoVNASaver/Charts/MagnitudeZShunt.py
- NanoVNASaver/Charts/RI.py
- NanoVNASaver/Charts/RISeries.py
- NanoVNASaver/Charts/RIShunt.py
- NanoVNASaver/Charts/__init__.py
- NanoVNASaver/NanoVNASaver.py
- NanoVNASaver/RFTools.py
Fixes #165
- Allows for both |Z| and R + jX display
- Measurements of shunt impedance (accurate for low impedance values)
as well as series impedance (accurate for high impedance values)
> Added measurement graphs showing impedance measured via S21

- NanoVNASaver/Charts/Frequency.py
- NanoVNASaver/Charts/MagnitudeZ.py
- NanoVNASaver/Charts/Permeability.py
- NanoVNASaver/Charts/RI.py
- NanoVNASaver/Charts/VSWR.py
Some further improvements for #165
- Now allows for plotting |Z| on a log axis
- Formats 1000000 as 1.000 M for improved readability
- A bit of cleanup to reduce code duplication from other charts that allow log-y data
> Adding support for |Z| plots with logarithmic scale and some cleanup

- NanoVNASaver/Controls/MarkerControl.py
- NanoVNASaver/Controls/SweepControl.py
- NanoVNASaver/Marker/Widget.py
- NanoVNASaver/NanoVNASaver.py
Improve usability on older laptops that are often used as lab pc, with font size <= 10 it's less than 720 pixel high, bigger font size increases the height slightly.
Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>
> smaller gui that fits completely on smaller screen, e.g.HD1280x720

- NanoVNASaver/SweepWorker.py
Caveat emptor - I know very little about VNA measurements.
But it seems to me the offset delay is something that should be applied only after calibrating to the reference plane?
> Apply offset delays _after_ calibration

- NanoVNASaver/Charts/Capacitance.py
- NanoVNASaver/Charts/Inductance.py
- NanoVNASaver/Charts/RI.py
Fixes #424 and #426 via "option 1" as mentioned in the issue discussion
> Some minor fixes in plotting

- test/test_sitools.py
test/test_sitools.py is failing with NameError: name 'Decimal' is not defined
> Fixing test runner

- nanovna-saver.py
I like run
`# <path>/nanovna-saver.py`
from directory containing my files ( calibration, saved s11, etc )
so I can organize my stuff.
> Add shebang and make nanovna-saver.py  executable

- NanoVNASaver/Hardware/VNA.py
Fixed the BW bug described in https://github.com/NanoVNA-Saver/nanovna-saver/issues/458
and added a few more common ones.
> fix for issue #458

- NanoVNASaver/Calibration.py
- NanoVNASaver/SweepWorker.py
- NanoVNASaver/Windows/CalibrationSettings.py
This is an enhancement/bugfix for issue https://github.com/NanoVNA-Saver/nanovna-saver/issues/349
Code author is @PA0JOZ, I did the rebase and minor bugfixes.
> PA0JOZ Enhanced Response Correction

- NanoVNASaver/Charts/Frequency.py
- NanoVNASaver/Formatting.py
could close https://github.com/NanoVNA-Saver/nanovna-saver/issues/438
> use more digit in format frequency when span is narrow

- NanoVNASaver/Controls/MarkerControl.py
- NanoVNASaver/NanoVNASaver.py
If You check "reference" with "Enable Delta Marker", calculate differences from reference.
Now, if no reference data, do not display values nor error.
May be needs some changes, but still could be useful for  https://github.com/NanoVNA-Saver/nanovna-saver/issues/493
> delta reference

- NanoVNASaver/Charts/Chart.py
- NanoVNASaver/Charts/Frequency.py
- NanoVNASaver/Charts/TDR.py
> enable to zoom out (not perfect yet)

- NanoVNASaver/Charts/Frequency.py
- NanoVNASaver/Charts/RI.py
- NanoVNASaver/Charts/SParam.py
- NanoVNASaver/Charts/Smith.py
- NanoVNASaver/Charts/TDR.py
Using more integer divisions to get right type for QPainter points
> Use more integer devisions

- NanoVNASaver/Charts/Frequency.py
> bugfix for python3.8 compatability

- .gitignore
- Makefile
- setup.cfg
Signed-off-by: Martin <Ho-Ro@users.noreply.github.com>
- type `make rpm` to build an (experimental) rpm package
that can be easily installed and removed on your local system
similar to the `make deb` PR.
-
-
> feat: experimental rpm build (works on a debian system)

- NanoVNASaver/Charts/TDR.py
- NanoVNASaver/Windows/TDR.py
- requirements.txt
Issue Number:  #586
- won't crash any longer
-
-
> fix numpy related crash in tdr modules

- setup.cfg
The library gets installed, but not the executable.
Also install the executable.
(As was the behavior before the most recent commit.)
> restore options.entry_points

- src/NanoVNASaver/Charts/Frequency.py
- src/NanoVNASaver/Charts/TDR.py
- src/NanoVNASaver/Hardware/NanoVNA.py
- src/NanoVNASaver/NanoVNASaver.py
- src/NanoVNASaver/Settings/Bands.py
- src/NanoVNASaver/Windows/Bands.py
- src/NanoVNASaver/Windows/CalibrationSettings.py
- src/NanoVNASaver/Windows/DisplaySettings.py
- src/NanoVNASaver/Windows/Files.py
More fixes for PyQt6: should now be usable again with >python3.7 & PyQt6
Calibration - tested
Display Configuration - tested
This should close allot of bugs containing "attribute not found" 
Single
- [X ] Bugfix
Lots of crashes due to the partial migration to the PyQt6 API
- Should be usable at least.
- [X ] No
> fix: PyQt6 fixes

- src/NanoVNASaver/About.py
Check for new version gives a connection error
Issue Number: #638
Check for new version is ok.
> use correct URL for NanoVNASaver version check

- src/NanoVNASaver/Windows/About.py
- Info and version check closer together
- More precise wording
- Reflect the connection status of the VNA
> Redesign of the About window

- AUTHORS.rst
- src/NanoVNASaver/Hardware/Hardware.py
- src/NanoVNASaver/Hardware/JNCRadio_VNA_3G.py
- src/NanoVNASaver/Hardware/VNA.py
- src/NanoVNASaver/Windows/DeviceSettings.py
Changes in Windows/ and Hardware/ to support this new device. Will be recognized as (JNCRadio) and adds support for Custom points and SN under Manage tab.
- [X ] Feature
Issue Number: 651
Sysjoint-Tek / CHELEGANCE JNCRadio VNA 3G support added. Custom points and SN available in Manage screen.
-
-
-
- [X ] No
> Jncradiovna3g - support Sysjoint-Tek / CHELEGANCE JNCRadio VNA 3G

- .gitignore
- nanovna-saver.py
- src/NanoVNASaver/Controls/SweepControl.py
- src/NanoVNASaver/Hardware/JNCRadio_VNA_3G.py
- src/NanoVNASaver/Hardware/SV4401A.py
- src/NanoVNASaver/Hardware/SV6301A.py
- src/NanoVNASaver/Marker/Values.py
- src/NanoVNASaver/NanoVNASaver.py
- src/NanoVNASaver/Settings/Sweep.py
- src/NanoVNASaver/Version.py
- src/NanoVNASaver/Windows/About.py
- src/NanoVNASaver/Windows/CalibrationSettings.py
- src/NanoVNASaver/Windows/DeviceSettings.py
- src/NanoVNASaver/Windows/DisplaySettings.py
> fix swwep update crash #668

- .github/workflows/release_win.yml
- [] Feature
-
-
-
- [] Yes
- [] No
> FIX build for windows executable (#702)

- .gitignore
- build-macos-app.sh
I just updated the existing script to compile on MacOS
- [] Bugfix
- [] Feature
Ensure support for MacOS
- [] Yes
I build and tested on a LiteVNA and everithing work a expected
> MacOS update script

- docs/INSTALLATION.md
Clarifies confusion as seen in discussion of issue #718
- [] Bugfix
- [] Feature
No mention of the macos build script, but only a more manual process that involves installing dependencies globally rather than in a venv as the build script does
Issue Number: #718 
- Add documentation of the process to use the build script, and explanation of where the executable file it creates is located.
- [] Yes
> Update INSTALLATION.md to mention automated macos build script

- pyproject.toml
- [] Feature
-
-
-
- [] Yes
- [] No
> fixed pyproject.toml

- pyproject.toml
- src/NanoVNASaver/Windows/TDR.py
- [] Feature
-
-
-
- [] Yes
- [] No
> Feature/version 0.6.6

- src/NanoVNASaver/Charts/TDR.py
- src/NanoVNASaver/Windows/TDR.py
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
- [] No
> fix: numpy cast warning

- pyproject.toml
- src/NanoVNASaver/Analysis/AntennaAnalysis.py
- src/NanoVNASaver/Analysis/BandPassAnalysis.py
- src/NanoVNASaver/Analysis/Base.py
- src/NanoVNASaver/Analysis/HighPassAnalysis.py
- src/NanoVNASaver/Charts/Chart.py
- src/NanoVNASaver/Charts/Frequency.py
- src/NanoVNASaver/Charts/LogMag.py
- src/NanoVNASaver/Charts/RI.py
- src/NanoVNASaver/Charts/TDR.py
- src/NanoVNASaver/NanoVNASaver.py
- src/NanoVNASaver/SITools.py
- src/NanoVNASaver/SweepWorker.py
- src/NanoVNASaver/Windows/TDR.py
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
- [] No
> linting and some refactoring

- pyproject.toml
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
- [] No
> add script section in pyproject.tomp

- src/NanoVNASaver/Analysis/AntennaAnalysis.py
- src/NanoVNASaver/Analysis/Base.py
- src/NanoVNASaver/Analysis/VSWRAnalysis.py
- src/NanoVNASaver/Controls/SerialControl.py
- src/NanoVNASaver/Defaults.py
- src/NanoVNASaver/Formatting.py
- src/NanoVNASaver/Hardware/Hardware.py
- src/NanoVNASaver/Hardware/NanoVNA.py
- src/NanoVNASaver/Hardware/NanoVNA_F.py
- src/NanoVNASaver/Hardware/NanoVNA_V2.py
- src/NanoVNASaver/Hardware/TinySA.py
- src/NanoVNASaver/Hardware/VNA.py
- src/NanoVNASaver/Settings/Sweep.py
- src/NanoVNASaver/SweepWorker.py
- src/NanoVNASaver/Windows/DeviceSettings.py
- src/NanoVNASaver/Windows/DisplaySettings.py
- src/NanoVNASaver/Windows/Files.py
> fix crash on device settings

- src/NanoVNASaver/Settings/Sweep.py
- [] Feature
-
-
-
- [] Yes
- [] No
> fix sweep init refactoring glitch

- .github/workflows/release_linux.yml
- src/NanoVNASaver/SweepWorker.py
- tests/test_truncate.py
- [] Feature
-
-
-
- [] Yes
- [] No
> fix crash when truncating averages

- src/NanoVNASaver/Hardware/LiteVNA64.py
- src/NanoVNASaver/Hardware/NanoVNA_F_V3.py
- src/NanoVNASaver/Hardware/NanoVNA_H4.py
A few leftovers from https://github.com/NanoVNA-Saver/nanovna-saver/pull/754
- [] Feature
- (LiteVNA) initial connect takes some time
- (NanoVNA-F_V3) feature reading may be broken
- (LiteVNA) initial connect takes less then 2 seconds
- (NanoVNA-F_V3) feature reading should works
- [] Yes
> Fix issues from LiteVNA related PR

- .pylintrc
- src/NanoVNASaver/Controls/SerialControl.py
- src/NanoVNASaver/Hardware/Hardware.py
- src/NanoVNASaver/Hardware/NanoVNA.py
- src/NanoVNASaver/Hardware/NanoVNA_V2.py
- src/NanoVNASaver/Hardware/TinySA.py
- src/NanoVNASaver/Hardware/VNA.py
- src/NanoVNASaver/Windows/About.py
- src/NanoVNASaver/Windows/Screenshot.py
- src/NanoVNASaver/Windows/SweepSettings.py
- src/NanoVNASaver/Windows/TDR.py
- src/NanoVNASaver/Windows/ui/__init__.py
- src/NanoVNASaver/__main__.py
- src/NanoVNASaver/utils/app_versions.py
- src/tools/project_clean.py
- uv.lock
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
> chore: linting with black and ruff

- docs/man/NanoVNASaver.1
The manual page documents one of the two installed executables.
- [] No
> Manual page: document the two installed executables

- src/NanoVNASaver/Windows/DisplaySettings.py
- uv.lock
> fix: crashing / not adding markers #769

- pyproject.toml
- src/NanoVNASaver/Windows/ui/__init__.py
- src/NanoVNASaver/Windows/ui/about.py
- uv.lock
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
> chore: linting

- .github/workflows/release_linux.yml
- .github/workflows/release_win.yml
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
> test: binary builds

- AUTHORS.rst
- README.rst
- [] Bugfix
- [] Feature
-
-
-
- [] Yes
> chore: update documentation

- src/NanoVNASaver/Windows/SweepSettings.py
> fix: band sweep setting #798

- debug.sh
- src/NanoVNASaver/Charts/Frequency.py
- src/NanoVNASaver/Marker/Widget.py
> fix: key navigation of markers. fixes #800

- src/NanoVNASaver/Charts/TDR.py
> chore: code fixes for mypy

- build-macos-app.sh
The macOS build script (`build-macos-app.sh`) fails to execute because:
1. It tries to install dependencies from `requirements.txt` which no longer exists in the repository
2. It calls `python3 setup.py -V` but the project no longer uses `setup.py`
3. It doesn't compile UI files before attempting to import NanoVNASaver, causing import errors
4. PyInstaller may not be available in the PATH after installation
Issue Number: #803 
- Fixed dependency installation by using `pip install -e ".[dev]"` to install from `pyproject.toml` instead of the missing `requirements.txt`
- Added UI compilation step (`python3 -m tools.ui_compile`) to generate required Python files from `.ui` files before importing NanoVNASaver
- Replaced `python3 setup.py -V` …
> Fix macOS build script
